### ISSUE TITLE
Build failure with containers 0.6

### ISSUE THREAD

**Issue by hsenag** [ChrisKuklewicz/regex-tdfa#17]
Looks like the API has changed around.

Would you mind also editing the constraints on hackage for existing releases?

```
Building library for regex-tdfa-1.2.3..
[ 1 of 23] Compiling Data.IntMap.CharMap2 ( Data/IntMap/CharMap2.hs, dist/build/Data/IntMap/CharMap2.o )

Data/IntMap/CharMap2.hs:153:24: error:
    • Data.IntMap.fold' is gone. Use Data.IntMap.foldr or Prelude.foldr.
    • In the expression: M.fold f a m
      In an equation for ‘fold’: fold f a (CharMap m) = M.fold f a m
    |
153 | fold f a (CharMap m) = M.fold f a m
    |                        ^^^^^^^^^^^^

Data/IntMap/CharMap2.hs:156:31: error:
    • Data.IntMap.foldWithKey is gone. Use foldrWithKey.
    • In the expression: M.foldWithKey f' a m
      In an equation for ‘foldWithKey’:
          foldWithKey f a (CharMap m)
            = M.foldWithKey f' a m
            where
                f' b a1 a2 = f (unsafeChr b) a1 a2
    |
156 | foldWithKey f a (CharMap m) = M.foldWithKey f' a m
    |                               ^^^^^^^^^^^^^^^^^^^^

Data/IntMap/CharMap2.hs:253:24: error:
    • Data.IntMap.showTree has moved to Data.IntMap.Internal.Debug.showTree
    • In the expression: M.showTree m
      In an equation for ‘showTree’: showTree (CharMap m) = M.showTree m
    |
253 | showTree (CharMap m) = M.showTree m
    |                        ^^^^^^^^^^^^

Data/IntMap/CharMap2.hs:256:34: error:
    • Data.IntMap.showTreeWith has moved to Data.IntMap.Internal.Debug.showTreeWith
    • In the expression: M.showTreeWith b1 b2 m
      In an equation for ‘showTreeWith’:
          showTreeWith b1 b2 (CharMap m) = M.showTreeWith b1 b2 m
    |
256 | showTreeWith b1 b2 (CharMap m) = M.showTreeWith b1 b2 m
    |                                  ^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by hvr** [comment]
I've gone ahead and revised 12 past releases at

 - https://hackage.haskell.org/package/regex-tdfa-1.1.1/revisions/
 - https://hackage.haskell.org/package/regex-tdfa-1.1.2/revisions/
 - https://hackage.haskell.org/package/regex-tdfa-1.1.3/revisions/
 - https://hackage.haskell.org/package/regex-tdfa-1.1.4/revisions/
 - https://hackage.haskell.org/package/regex-tdfa-1.1.6/revisions/
 - https://hackage.haskell.org/package/regex-tdfa-1.1.7/revisions/
 - https://hackage.haskell.org/package/regex-tdfa-1.1.8/revisions/
 - https://hackage.haskell.org/package/regex-tdfa-1.2.0/revisions/
 - https://hackage.haskell.org/package/regex-tdfa-1.2.1/revisions/
 - https://hackage.haskell.org/package/regex-tdfa-1.2.2/revisions/
 - https://hackage.haskell.org/package/regex-tdfa-1.2.3/revisions/


Please use accurate version bounds in future in order to avoid such regression for Hackage users as well as reduce the workload for Hackage Trustees. Thank you!

**Comment by neongreen** [comment]
> Looks like the API has changed around.

I'm on it.

**Comment by neongreen** [comment]
Released regex-tdfa-1.2.3.1.

**Comment by neongreen** [comment]
(I've also added version bounds)

**Comment by hsenag** [comment]
Many thanks for the fast response.
